## Numpy

In [ ]:
import numpy as np

In [ ]:
# Python list

# 1 axis(軸)
[0, 1, 2, 3]  # 4個元素, 長度4

# 2 axes
[[0, 1, 2, 3],
 [4, 5, 6, 7]]
 # 第0個軸長度2
 # 第1個軸長度4

### 創造 numpy.ndarray

In [2]:
# 生成 1 axis array，數值0~3(不包括)
x = np.arange(3) # range(3)

print(x) # [0, 1, 2]
print(type(x))  # <class 'numpy.ndarray'>

# 指定數值類型
y = np.arange(5, dtype=np.float64) # 64位元浮點數
print(y) # [0. 1. 2. 3. 4.]

[0 1 2]
<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.]


### Python List 轉成 numpy.ndarray

In [3]:
python_list = [55, 66]

numpy_array = np.array(python_list)

print(python_list, type(python_list)) # [55, 66] <class 'list'>
print(numpy_array, type(numpy_array)) # [55 66] <class 'numpy.ndarray'>

[55, 66] <class 'list'>
[55 66] <class 'numpy.ndarray'>


### np.ndarray attributes (屬性)

In [4]:
# 1D array
x = np.arange(3)
print(x) # [0, 1, 2]

# dim: 維度(rank)
# ndim - 軸(維度數量) axes (dimensions)
print(x.ndim) # 1 dim(維)

# !!! shape: array形狀
print(x.shape) # (3, )

# size: 元素總數
print(x.size) # 3

# dtype: 數值類型
print(x.dtype)  # np.int64: 64位元整數

[0 1 2]
1
(3,)
3
int64


In [5]:
# 2D array
x = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
print(x)
# [[0 1 2]
#  [3 4 5]]

# ndim - number of axes (dimensions)
print(x.ndim) # 2 dim(維)

# !!! shape: array形狀
print(x.shape) # (2, 3)

# size: 元素總數
print(x.size) # 6

[[0 1 2]
 [3 4 5]]
2
(2, 3)
6


### Numpy Array 改變形狀(reshape)

NOTE: 改變形狀前後數值內容與數量不變

In [6]:
# reshape
x = np.arange(6)
print(x)  # [0 1 2 3 4 5]

# Method 1: np.ndarray.reshape()
new_shape = x.reshape(3, 2)
print(new_shape)
# [[0 1]
#  [2 3]
#  [4 5]]

# Method 2: np.reshape()
new_shape = np.reshape(x, (3, 2))

# 一行流
y = np.arange(6).reshape(2, 3)

# -1: 自動計算形狀
new_shape = x.reshape(3, -1)
new_shape, new_shape.shape

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


(array([[0, 1],
        [2, 3],
        [4, 5]]),
 (3, 2))

### 使用數值初始化創造np.ndarray

In [7]:
# np.zeros: 全0
np.zeros(2)  # array([ 0.,  0.])
np.zeros((2, 3))
# array([[ 0.,  0.,  0.],
#        [ 0.,  0.,  0.]])

# np.ones: 全1
np.ones((2, 3))
# array([[ 1.,  1.,  1.],
#        [ 1.,  1.,  1.]])

# np.full: 全部指定某數值
np.full(shape=(2, 3), fill_value=5566)
# array([[5566, 5566, 5566],
#        [5566, 5566, 5566]])

array([[5566, 5566, 5566],
       [5566, 5566, 5566]])

### 使用隨機值創造np.ndarray

In [8]:
# Uniform distribution(均勻分佈): [0, 1), 每個數值出現機率相同
print(np.random.random(size=(2, 2)))

# Normal distributution(常態分佈)
# loc: mean 平均
# scale: std 標準差
print(np.random.normal(loc=0.0, scale=1.0, size=(2, 2)))

# 隨機整數
# low: 下限(包含)
# high: 上限(不包含)
print(np.random.randint(low=1, high=10, size=(5, 5)))

[[0.70843311 0.81409883]
 [0.7111285  0.67153178]]
[[-1.31073162 -0.02606378]
 [-0.81803072 -0.38147688]]
[[3 2 5 8 9]
 [2 1 8 4 8]
 [3 3 9 5 6]
 [6 5 8 6 1]
 [7 7 9 3 4]]


### Array Index (索引)

NOTE: 從0開始

In [ ]:
# 1D array
x = np.arange(6)
# array([0, 1, 2, 3, 4, 5])
x[1]   # 第1個值: 1
x[-3]  # 倒數第3個值: 3

# 2D array
x = np.arange(6).reshape(2, 3)
#[[0, 1, 2],
# [3, 4, 5]])

# axis0 第0個
# axis1 第1個
x[0, 1] # 1

# axis0 第1個
# axis1 倒數第2個
x[1, -2] # 4

### Array Slice(切片) & Stride(步長)

```python
array[開始:結束]

array[開始:結束:步長]
```
NOTE: 省略開始位置即為從頭開始，省略結束位置即為取至最後一個

NOTE: 不包含結束index位置的數值

In [ ]:
# 1D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[1:5]   # [1, 2, 3, 4]
x[1:] # x[1:6]: [1, 2, 3, 4, 5]
x[:3] # x[0:3] , [0, 1, 2]
x[1:4:2] # [1, 3], stride=2 每次跳2個位置

# 2D array
x = np.arange(6).reshape(2, 3)
#[[0, 1, 2],
# [3, 4, 5]])

x[0, 0:2]
# [0, 1]

x[:, 1:]
# [[1, 2],
#  [4, 5]]

x[::1, ::2]
# [[0, 2],
#  [3, 5]]

# Reverse axis: 某個軸數值反向
# ex: BGR -> RGB
# (100, 100, 3)

print('original: \n', x)
print('reverse axis1: \n', x[:, ::-1] )
# [[2, 1, 0],
#  [5, 4, 3]]

### 條件篩選 & 賦值: Boolean / Mask Index

&: and

|: or

~: not

In [ ]:
import numpy as np

x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
condition = x<4
x[condition] # [0, 1, 2, 3]
x[x<4] # [0, 1, 2, 3]

# 串連條件: and, or, not
print('>=1 and <4:', x[(x>=1) & (x<4)])
print('<=1 or >4 :', x[(x<=1) | (x>4)])
print('not > 4   :', x[~(x>4)])

# 條件賦值
x[condition] = 0
x[x<4] = 0
x # [0, 0, 0, 0, 4, 5]

# Bool mask 邏輯：
# original x      # [ 0, 1, 2, 3, 4, 5]
# if <4, assign 0
print('condition:', condition) # [ True  True  True True  False False]
print('x        :', x) # [ 0,    0,    0,   0,    4,    5]

### np.concatenate: 串接array

沿著某個軸(axis)串接



In [9]:
x = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
y = np.array([
    [6, 7, 8]
])
z = np.array([
    [55],
    [66]
])
print('x.shape', x.shape) # (2, 3)
print('y.shape', y.shape) # (1, 3)
print('z.shape', z.shape) # (2, 1)

a = np.concatenate((x, y), axis=0)
print('concat(x, y) shape:', a.shape) # (3, 3)
print(a)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]
b = np.concatenate((x, z), axis=1)
print('concat(x, z) shape:', b.shape) # (2, 4)
print(b)
# [[ 0  1  2 55]
#  [ 3  4  5 66]]

x.shape (2, 3)
y.shape (1, 3)
z.shape (2, 1)
concat(x, y) shape: (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
concat(x, z) shape: (2, 4)
[[ 0  1  2 55]
 [ 3  4  5 66]]


### 基本運算

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 5], [6, 7]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a - 3)
print(a * 2)
print('power: \n', a ** 2) # 次方
print('quotient: \n', a // 2) # 整除(商)
print('Remainder: \n', a%2) # 餘數

sqrt_array = np.sqrt(a) #根號
exp_array = np.exp(a) # exponential次方
log_array = np.log(a) # 自然對數

print("Square root:\n", sqrt_array)
print("Exponential:\n", exp_array)
print("Natural logarithm:\n", log_array)

### 基礎統計量

In [10]:
x = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(np.min(x), x.min())
print(np.max(x), x.max())
print(np.mean(x), x.mean())
print(np.std(x), x.std())

0 0
9 9
4.5 4.5
2.8722813232690143 2.8722813232690143


In [11]:
# argmax, argmin: 最大 最小值的位置(index)
x = np.random.randint(0, 10, 6)
print(x)
print('np.argmax:', np.argmax(x))
print('np.argmin:', np.argmin(x))

[8 4 6 9 1 2]
np.argmax: 3
np.argmin: 4


### 插入/刪除維度: expand_dim & squeeze

NOTE: 插入與刪除的維度都是1

In [12]:
x = np.ones((128, 128))
print(x.shape) # (128, 128)

x = np.expand_dims(x, axis=0)
print(x.shape) # (1, 128, 128)

x = np.expand_dims(x, axis=-1)
print(x.shape) # (1, 128, 128, 1)

x = np.squeeze(x, axis=-1)
print(x.shape) # (1, 128, 128)

(128, 128)
(1, 128, 128)
(1, 128, 128, 1)
(1, 128, 128)


### 尋找不重複數值: np.unique

return_counts: 計算出現次數

In [13]:
x = np.random.randint(low=0, high=10, size=(10, ))
print(x)

# 唯一值
values = np.unique(x)
print('unique values: ', values)

# 唯一值 + 個數
values, counts = np.unique(x, return_counts=True)
print('counts:        ', counts)

[6 4 6 0 0 7 2 4 2 6]
unique values:  [0 2 4 6 7]
counts:         [2 2 2 3 1]


In [ ]:
np.arange(0, 10, step=3)

## Reference Answers for Exercises

#### Q1 Create a 1D array with values from 10 to 19 **(Hint: np.arange)**

In [ ]:
# 1
x = np.arange(10, 20)
print(x)

#### Q2: Reverse a vector
ex: [0, 1, 2] -> [2, 1, 0]

In [ ]:
# 2
x = np.arange(6)
x = x[::-1]
print(x)

#### Q3: Create a 3x3x3 array with random values
**(Hint: np.random.random or np.random.normal)**

In [ ]:
# 3
x = np.random.random((3, 3, 3))
print(x)

#### Q4. Create a 5x5 array with random values and find the minimum and maximum
**(Hint: np.min, np.max)**

In [ ]:
# 4
x = np.random.random((5, 5))
xmin, xmax = np.min(x), np.max(x) # or x.min(), x.max()
print(xmin, xmax)

#### Q5 :Add a border (filled with 0's) around an 3 * 3 matrix with width 1
**Hint: np.pad**

In [ ]:
# 5
x = np.ones((3, 3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

#### Q6. Normalize a 3x3 random matrix to 0~1
**(Hint: (x - x min) / (x max - x min))**

In [ ]:
# 6
x = np.random.random((3, 3))
x2 = (x - np.min(x)) / (np.max(x) - np.min(x))
print(x)
print(x2)

#### Q7. Given a 1D array (0 ~ 12), negate all elements which are between 2 and 9.
ex: [2, 3, 4, 10, 11] -> [-2, -3, -4, 10, 11]

In [ ]:
# 7
x = np.arange(2, 12)
x[(2 < x) & (x < 9)] *= -1
print(x)

Q8. Extract from the array [6, 7, 8, 10, 24, 45, 99,100] by the below conditions
 1. which are not divisible by 3
 2. which are divisible by 5
 3. which are divisible by 3 and 5

In [ ]:
# 8
x = np.array([6, 7, 8, 10, 24, 45, 99,100])
div3 = x[x%3 != 0]
print(div3)

div5 = x[x%5 == 0]
print(div5)

div15 = x[(x%3 == 0) & (x%5 == 0)]
print(div15)

#### Q9. Create random vector of size 10 and replace the maximum value by 0
**Hint: np.argmax**

In [ ]:
# 9
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

#### Q10. Create a 4x4 matrix and the row values are from 0 to 3

In [ ]:
# 10
x = np.zeros((4, 4))
x += np.arange(4)
print(x)